// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function ConfigureGorm(arg1, arg2, arg3, arg4, arg5, arg6) {
  return window['go']['main']['App']['ConfigureGorm'](arg1, arg2, arg3, arg4, arg5, arg6);
}

export function GenerateOpenApi() {
  return window['go']['main']['App']['GenerateOpenApi']();
}

export function GetTablesList() {
  return window['go']['main']['App']['GetTablesList']();
}

export function GraphTransform() {
  return window['go']['main']['App']['GraphTransform']();
}

export function PerformAllVerifications() {
  return window['go']['main']['App']['PerformAllVerifications']();
}
