// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {api} from '../models';
import {dbstructs} from '../models';

export function ConfigureGorm(arg1:string,arg2:string,arg3:string,arg4:string,arg5:string,arg6:string):Promise<string>;

export function GenerateOpenApi(arg1:api.APIConfig):Promise<string>;

export function GetTablesList():Promise<Array<dbstructs.TableMetadata>>;

export function GraphTransform():Promise<string>;

export function PerformAllVerifications():Promise<string>;
